development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: redis://redistogo:8ec9ea479d4c68f91fdeb0acc92caeaa@pike.redistogo.com:10793/
  channel_prefix: instatalk_production
